Map<String, String> arLang = {
  //header
  'invoice_date': 'تاريخ الفاتورة',
  'due_date': 'تاريخ الاستحقاق',
  'payment_method': 'طريقة الدفع',
  'cash': 'نقدي',
  'supplier_info': 'بيانات المورد',
  'name': 'الاسم:',
  'address': 'العنوان:',
  'city': 'المدينة:',
  'country': 'الدولة:',
  'phone': 'الهاتف:',
  'email': 'البريد الإلكتروني:',
  'client': 'العميل',
  'tax_invoice': 'فاتورة ضريبية',
  'one_hundred_and_five_sar_only': 'مئة وخمسة ريال سعودي فقط لا غير',

  'statement': 'البيان',
  'without_carton': 'بدون كرتون',

  'item': 'م',
  'category_name': 'اسم التصنيف',
  'unit': 'الوحدة',
  'quantity': 'الكمية',
  'free_quantity': 'الكمية المجانية',
  'price': 'السعر',
  'vat': 'ضريبة قيمة مضافة %',
  'total': 'الإجمالي',
  'page': 'صفحة',
  'from': 'من',
  'all_rights_reserved': 'جميع الحقوق محفوظة لدي شركة Ultimate Solutions',
  
  'total_amount': 'الإجمالي: @amount@ SAR',
  'discount': 'الخصم: @discount@',
  'tax_total': 'إجمالي الضريبة: @tax@',
  'burden_total': 'إجمالي الأعباء: @burden@',
  'total_with_tax': 'الإجمالي بالضريبة: @total_with_tax@ SAR',

  'amount_in_words': 'مائة وخمسة ريال سعودي فقط',
  'postal_code': 'الرمز البريدي',
  'tax_no': 'الرقم الضريبي',
  'tax_crn': 'CRN الضريبي',
  'other': 'آخر',

  "supplier_name": "اسم المورد",
  "client_name": "اسم العميل",
  "supplier_address": "عنوان المورد",
  "supplier_city": "مدينة المورد",
  "supplier_country": "بلد المورد",
  "client_address": "عنوان العميل",
  "client_city": "مدينة العميل",
  "client_country": "بلد العميل",

  "description": "الوصف",

  "supplier_postal_code": "الرمز البريدي للمورد",
  "supplier_tax_no": "رقم ضريبة المورد",
  "supplier_tax_crn": "رقم تسجيل ضريبة المورد",
  "supplier_other": "بيانات أخرى للمورد",
  "client_postal_code": "الرمز البريدي للعميل",
  "client_tax_no": "رقم ضريبة العميل",
  "client_tax_crn": "رقم تسجيل ضريبة العميل",
  "client_other": "بيانات أخرى للعميل",
  'add_items': 'إضافة عناصر',
  'pick_logo_image': 'اختيار صورة الشعار',
  'pick_qr_code_image': 'اختيار صورة رمز الاستجابة السريعة',
  'generate_pdf': 'إنشاء ملف PDF',
  'pdf_form_title': 'عنوان نموذج PDF',
};
