Map<String, String> enLang = {
  //header
  "invoice_date": "Invoice Date",
  "due_date": "Due Date",
  "payment_method": "Payment Method",
  "cash": "Cash",
  "supplier_info": "Supplier Information",
  "name": "Name:",
  "address": "Address:",
  "city": "City:",
  "country": "Country:",
  "phone": "Phone:",
  "email": "Email:",
  "client": "Client",
  "tax_invoice": "Tax Invoice",
  "one_hundred_and_five_sar_only": "One Hundred and Five Saudi Riyals Only",

  "statement": "Statement",
  "without_carton": "Without Carton",

  "item": "Item",
  "category_name": "Category Name",
  "unit": "Unit",
  "quantity": "Quantity",
  "free_quantity": "Free Quantity",
  "price": "Price",
  "vat": "VAT %",
  "total": "Total",
  "all_rights_reserved": "All rights reserved by Ultimate Solutions",
  'page': 'Page',
  'from': 'From',
  "total_amount": "Total Amount: 91.30 SAR",
  "discount": "Discount: 0.00",
  "tax_total": "Tax Total: 13.70",
  "burden_total": "Burden Total: 0.00",
  "total_with_tax": "Total with Tax: 105 SAR",
  "amount_in_words": "One Hundred and Five Saudi Riyals Only",
  'postal_code': 'Postal Code',
  'tax_no': 'Tax Number',
  'tax_crn': 'Tax CRN',
  'other': 'Other',

  'supplier_name': 'Supplier Name',
  'client_name': 'Client Name',
  'supplier_address': 'Supplier Address',
  'supplier_city': 'Supplier City',
  'supplier_country': 'Supplier Country',
  'client_address': 'Client Address',
  'client_city': 'Client City',
  'client_country': 'Client Country',

  'description': 'Description',

  'supplier_postal_code': 'Supplier Postal Code',
  'supplier_tax_no': 'Supplier Tax Number',
  'supplier_tax_crn': 'Supplier Tax CRN',
  'supplier_other': 'Supplier Other',
  'client_postal_code': 'Client Postal Code',
  'client_tax_no': 'Client Tax Number',
  'client_tax_crn': 'Client Tax CRN',
  'client_other': 'Client Other',

  'add_items': 'Add Items',
  'pick_logo_image': 'Pick Logo Image',
  'pick_qr_code_image': 'Pick QR Code Image',
  'generate_pdf': 'Generate PDF',
  'pdf_form_title': 'PDF Form Title',
};
